# Exercícios práticos em Python para explorar a aplicação de quatro bibliotecas diferentes.

## NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.


In [ ]:
import numpy as np

array = np.random.randint(10, 101, size=50)

print(array)

[45 35 87 11 20 70 30 11 79 62 33 66 40 28 34 74 46 10 62 97 25 21 44 36
 24 77 12 35 52 51 82 93 91 25 29 33 42 11 47 54 38 20 25 56 18 33 54 27
 90 14]


Foi utilizado o [.random] para randomizar os numeros e dentro dele o [.randint] para que fosse apenas numeros inteiros

Parametro de inicio 10 até o fim 100 com o tamanho de 50 numeros dentro do array



2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [ ]:
import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)

ultima_linha = matriz[-1]

print("Matriz completa:")
print(matriz)

print("\nÚltima linha:")
print(ultima_linha)

Matriz completa:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha:
[13 14 15 16]


Foi utilizado o [.arange] para gerar a sequência de números e junto a ele o [.reshape] para que fosse formatado em linhas e colunas.

Parâmetro de início 1 até o fim 17 (para incluir o 16) com o tamanho de 4x4 (4 linhas e 4 colunas) dentro da matriz.

E foi utilizado o índice [-1] na variável para extrair apenas a última linha da matriz.

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
`a 10ª posição por 1

In [ ]:
import numpy as np

array = np.zeros(15)

array[4:10] = 1

print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Foi utilizado o [.zeros] para criar um array apenas composto de 0(zeros) com a quantidade de 15

Foi utilizado o parametro [4:10] para colocar o valor 1 da posição 5 até a posição 10

4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

In [ ]:
import numpy as np

array = np.random.randint(1, 21, size=100)

mediana = np.median(array)
moda = np.bincount(array).argmax()

print("Array gerado:", array)
print("Mediana:", mediana)
print("Moda:", moda)


Array gerado: [ 6  6 17  8  4  8  6  2 14  3  9 17 17 10  6 12 16 19 14  1 12  2  1  3
 20 18 15 19 14 19  8  7 12 13  1  1 15 11 16  8  3 10  5 15  4  1 16  8
  7 10 16 15  8  1 15 15 19 19  4 14 10  5  1 17  3 14  2  1 17 13  9 15
 11  4 12  8  5  5 11 19 19 13  5 16 19 20  5 11  2 12 11  5  3  4 10 20
  3 19 11 11]
Mediana: 10.5
Moda: 19


Dentro da geração do array foi escolhido colocar o parametro de numeros de 1 a 20 para que existissem repetições

[np.median] foi utilizado para calcular a mediana do array

[np.bincount] foi utilizado para verificar quantas vezes cada numero apareceu dentro do array

[argmax()] foi utilizado na intenção de mostrar qual elemento apareceu mais vezes



5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por -3.

In [1]:
import numpy as np

array = np.random.randint(1, 101, size=20)

print("Array original:")
print(array)

array[array % 3 == 0] = -3

print("Array modificado:")
print(array)

Array original:
[30 23 31 56 91 48 77  2 34 84 72 15 32 55 13 65 28 64 12 84]
Array modificado:
[-3 23 31 56 91 -3 77  2 34 -3 -3 -3 32 55 13 65 28 64 -3 -3]


Foi criado um array aonde gera 20 numeros inteiros de 1 a 100

Utilizando o calculo [array % 3 == 0] vai calcular o modulo do de cada numero do array, caso o valor seja 0 no final o numero sera alterado para [-3]

6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna.

In [ ]:
import numpy as np

matriz = np.random.rand(5, 5)

print("Matriz completa:")
print(matriz)

soma_colunas = np.sum(matriz, axis=0)
print("Soma de cada coluna:", soma_colunas)


Matriz completa:
[[0.43145058 0.99831261 0.22207    0.77796099 0.22302143]
 [0.11380368 0.70563451 0.27129552 0.22130883 0.06704798]
 [0.12863495 0.5543265  0.35707538 0.43493585 0.15262331]
 [0.20049903 0.23444488 0.49452375 0.87523977 0.54863231]
 [0.12864356 0.88512515 0.92465686 0.87361091 0.31306845]]
Soma de cada coluna: [1.00303181 3.37784363 2.26962151 3.18305635 1.30439348]


A função np.random.rand(5, 5) faz uma matriz de 5 po 5 com apenas numeros de 0 a 1

A função axis=0 ela trabalha no eixo vertical, somando com a função np.sum realiza a soma de cada coluna da matriz de forma separada

7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [ ]:
import numpy as np

array1 = np.random.randint(1,15, size=10)
array2 = np.random.randint(1,15, size=10)

print("Array 1: ", array1)
print("Array 2: ", array2)

print("Correlação: ", np.corrcoef(array1, array2))

Array 1:  [ 5  7 12 10  8  2  2 14  7 10]
Array 2:  [11  5 13  1  7  5 10  1  8 10]
Correlação:  [[ 1.         -0.23696697]
 [-0.23696697  1.        ]]


Para a criação dos array`s foi utilizado o comando [np.random.randint] para que fosse gerado numeros inteiros aleatorios

Para a correlação foi utilizada a função np.corrcoef() com as 2 array`s criadas dentro da função


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.


In [3]:
import numpy as np

matriz = np.random.randint(1, 11, size=(3,3))

print("Matriz original:")
print(matriz)

print("Matriz ao quadrado:")
print(matriz**2)

Matriz original:
[[10  6  9]
 [ 1  4  7]
 [ 9  3  3]]
Matriz ao quadrado:
[[100  36  81]
 [  1  16  49]
 [ 81   9   9]]


Foi criado a matriz com numeros aleatorios e inteiros de 1 a 10 com a matriz de por 3

Para elevar a matriz ao quadrado não foi criado uma variavel nova para isso, e sim utilizando apenas uma formula matematica para elevar apenas no print

9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.


In [1]:
import numpy as np

array = np.random.randint(1, 11, size=10)

print("Array original:")
print(array)

valorMin = np.min(array)
valorMax = np.max(array)

arrayNormalizado = (array - valorMin) / (valorMax - valorMin)

arrayNormalizado = np.round(arrayNormalizado, 2)

print("Array normalizado:")
print(arrayNormalizado)


Array original:
[5 2 2 6 4 9 3 5 1 5]
Array normalizado:
[0.5  0.12 0.12 0.62 0.38 1.   0.25 0.5  0.   0.5 ]
