<a href="https://colab.research.google.com/github/76Falcone/AulasInteligenciaArtificial/blob/main/Exerc%C3%ADciosBibliotecas_Python_Falcone_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios práticos em Python para explorar a aplicação de quatro bibliotecas diferentes.

## NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.


In [ ]:
import numpy as np

array = np.random.randint(10, 101, size=50)

print(array)

[27 25 82 32 20 30 45 39 38 81 23 78 83 62 57 38 12 50 27 76 13 25 37 70
 23 19 36 34 12 67 26 89 30 50 84 41 78 43 20 32 62 22 41 32 87 18 82 47
 55 54]


Foi utilizado o [.random] para randomizar os numeros e dentro dele o [.randint] para que fosse apenas numeros inteiros

Parametro de inicio 10 até o fim 100 com o tamanho de 50 numeros dentro do array



2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [ ]:
import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)

ultima_linha = matriz[-1]

print("Matriz completa:")
print(matriz)

print("\nÚltima linha:")
print(ultima_linha)

Matriz completa:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha:
[13 14 15 16]


Foi utilizado o [.arange] para gerar a sequência de números e junto a ele o [.reshape] para que fosse formatado em linhas e colunas.

Parâmetro de início 1 até o fim 17 (para incluir o 16) com o tamanho de 4x4 (4 linhas e 4 colunas) dentro da matriz.

E foi utilizado o índice [-1] na variável para extrair apenas a última linha da matriz.

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
`a 10ª posição por 1

In [ ]:
import numpy as np

array = np.zeros(15)

array[4:10] = 1

print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Foi utilizado o [.zeros] para criar um array apenas composto de 0(zeros) com a quantidade de 15

Foi utilizado o parametro [4:10] para colocar o valor 1 da posição 5 até a posição 10