<a href="https://colab.research.google.com/github/76Falcone/AulasInteligenciaArtificial/blob/main/Exerc%C3%ADciosBibliotecas_Python_Falcone_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios práticos em Python para explorar a aplicação de quatro bibliotecas diferentes.

## NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.


In [88]:
import numpy as np

array = np.random.randint(10, 101, size=50)

print(array)

[90 80 16 12 73 55 25 37 31 49 35 28 93 15 18 17 69 30 33 25 49 88 23 71
 71 97 37 58 78 76 69 78 14 16 12 46 78 44 60 89 99 54 87 56 94 39 49 49
 84 57]


Foi utilizado o [.random] para randomizar os numeros e dentro dele o [.randint] para que fosse apenas numeros inteiros

Parametro de inicio 10 até o fim 100 com o tamanho de 50 numeros dentro do array



2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [89]:
import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)

ultima_linha = matriz[-1]

print("Matriz completa:")
print(matriz)

print("\nÚltima linha:")
print(ultima_linha)

Matriz completa:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha:
[13 14 15 16]


Foi utilizado o [.arange] para gerar a sequência de números e junto a ele o [.reshape] para que fosse formatado em linhas e colunas.

Parâmetro de início 1 até o fim 17 (para incluir o 16) com o tamanho de 4x4 (4 linhas e 4 colunas) dentro da matriz.

E foi utilizado o índice [-1] na variável para extrair apenas a última linha da matriz.

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
`a 10ª posição por 1

In [90]:
import numpy as np

array = np.zeros(15)

array[4:10] = 1

print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Foi utilizado o [.zeros] para criar um array apenas composto de 0(zeros) com a quantidade de 15

Foi utilizado o parametro [4:10] para colocar o valor 1 da posição 5 até a posição 10

4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

In [91]:
import numpy as np

array = np.random.randint(1, 21, size=100)

mediana = np.median(array)
moda = np.bincount(array).argmax()

print("Array gerado:", array)
print("Mediana:", mediana)
print("Moda:", moda)


Array gerado: [18 17  7 12 12  9  4  4 13 17 12  3 14  4  7  7 17 19 10 15 10 19 14 15
 12 16  5 19  6 19  7  2  9  4 16  6 10  6 16  6  7  4  1  7 10  2  9 17
 10  8 18  6 16  9 19  6 15 18  5  1  1  3  2 11 20  4 16 17 14 15 16 20
 19 13 15 15 16  9 12  6  8  6 16 12 11  9 14 10 15  2  7  4  1 18 16 15
 15 12 11 14]
Mediana: 11.0
Moda: 15


Dentro da geração do array foi escolhido colocar o parametro de numeros de 1 a 20 para que existissem repetições

[np.median] foi utilizado para calcular a mediana do array

[np.bincount] foi utilizado para verificar quantas vezes cada numero apareceu dentro do array

[argmax()] foi utilizado na intenção de mostrar qual elemento apareceu mais vezes



5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por -3.

In [92]:
import numpy as np

array = np.random.randint(1, 101, size=20)

print("Array original:")
print(array)

array[array % 3 == 0] = -3

print("Array modificado:")
print(array)

Array original:
[ 27  45  32  93  51  81  47  33  94  81  49  10  47  36  70 100  57  76
  34   5]
Array modificado:
[ -3  -3  32  -3  -3  -3  47  -3  94  -3  49  10  47  -3  70 100  -3  76
  34   5]


Foi criado um array aonde gera 20 numeros inteiros de 1 a 100

Utilizando o calculo [array % 3 == 0] vai calcular o modulo do de cada numero do array, caso o valor seja 0 no final o numero sera alterado para [-3]

6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna.

In [93]:
import numpy as np

matriz = np.random.rand(5, 5)

print("Matriz completa:")
print(matriz)

soma_colunas = np.sum(matriz, axis=0)
print("Soma de cada coluna:", soma_colunas)


Matriz completa:
[[0.58977627 0.1851007  0.74472214 0.66424484 0.47167388]
 [0.44196422 0.93129778 0.32183946 0.02584517 0.75698631]
 [0.60832597 0.89769966 0.144591   0.59071458 0.30822995]
 [0.87613063 0.92036787 0.88221305 0.39330675 0.04886664]
 [0.44416116 0.64069332 0.29481267 0.95722154 0.5068826 ]]
Soma de cada coluna: [2.96035825 3.57515933 2.38817833 2.63133289 2.09263937]


A função np.random.rand(5, 5) faz uma matriz de 5 po 5 com apenas numeros de 0 a 1

A função axis=0 ela trabalha no eixo vertical, somando com a função np.sum realiza a soma de cada coluna da matriz de forma separada

7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [94]:
import numpy as np

array1 = np.random.randint(1,15, size=10)
array2 = np.random.randint(1,15, size=10)

print("Array 1: ", array1)
print("Array 2: ", array2)

print("Correlação: ", np.corrcoef(array1, array2))

Array 1:  [ 1  7 12 13  6  9 12 14  4 10]
Array 2:  [14  8  7 13 14  3  2  5  4  6]
Correlação:  [[ 1.         -0.37336308]
 [-0.37336308  1.        ]]


Para a criação dos array`s foi utilizado o comando [np.random.randint] para que fosse gerado numeros inteiros aleatorios

Para a correlação foi utilizada a função np.corrcoef() com as 2 array`s criadas dentro da função


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.


In [95]:
import numpy as np

matriz = np.random.randint(1, 11, size=(3,3))

print("Matriz original:")
print(matriz)

print("Matriz ao quadrado:")
print(matriz**2)

Matriz original:
[[9 1 7]
 [6 3 5]
 [6 2 5]]
Matriz ao quadrado:
[[81  1 49]
 [36  9 25]
 [36  4 25]]


Foi criado a matriz com numeros aleatorios e inteiros de 1 a 10 com a matriz de por 3

Para elevar a matriz ao quadrado não foi criado uma variavel nova para isso, e sim utilizando apenas uma formula matematica para elevar apenas no print

9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.


In [96]:
import numpy as np

array = np.random.randint(1, 11, size=10)

print("Array original:")
print(array)

valorMin = np.min(array)
valorMax = np.max(array)

arrayNormalizado = (array - valorMin) / (valorMax - valorMin)

arrayNormalizado = np.round(arrayNormalizado, 2)

print("Array normalizado:")
print(arrayNormalizado)


Array original:
[ 4  2 10  5  2  4  4  7  5  2]
Array normalizado:
[0.25 0.   1.   0.38 0.   0.25 0.25 0.62 0.38 0.  ]


Foi utilizado o metodo [np.random.randint] para gerar um array de numeros de 1 a 10 com o tamanho do array de 10 componentes

Foi utilizado os metodos [np.min] e [np.max] para acessar o menor e o maior numero do array

Foi utilizada a fórmula de normalização (x - mínimo) / (máximo - mínimo) para calcular o valor normalizado de cada número do array, transformando os valores para uma escala entre 0 e 1.


10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

In [97]:
import numpy as np

matriz = np.eye(6)

indices = np.arange(6)
matriz[indices, indices] = np.arange(1, 7)

print(matriz)



[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


Foi utilizado o método [np.eye] para criar uma matriz identidade de tamanho 6x6, preenchendo a diagonal principal com valores 1 e as demais posições com 0.

Foi utilizado o método [np.arange] para criar os índices de 0 a 5, que representam as posições da diagonal principal da matriz.

Foi utilizado o comando [matriz[indices, indices]] para acessar as posições da diagonal principal e substituí-las pelos valores de 1 a 6.

Foi utilizado o método [np.arange(1, 7)] para gerar os valores crescentes de 1 a 6, que foram colocados na diagonal principal da matriz.


11. Gere um array de 100 números inteiros e encontre o valor que mais se
repete no array.

In [98]:
import numpy as np

array = np.random.randint(1, 11, size=100)

print("Array gerado: ")
print(array)

moda = np.bincount(array).argmax()

print("\nValor que mais se repete: ", moda)

Array gerado: 
[ 1 10  1  4  4  8  6  6  9 10  1 10  6  1  7  8  2  6  3  8  6  1  2  7
  5  5  9 10  3  9  8  5  7  1  5  8  1  3  4  6  7  3  9  1  1 10  6  8
  7  5  1  1  7  6  9  5  8  7 10  3  7  7  7  8  9  8  7  9  1  1  9  8
  9  5  3  4  7  5  6  4  1  5  2  1  8  8  4  5  1  9  8  8  8  6  8  9
  5  7 10  4]

Valor que mais se repete:  1


Foi utilizado o metodo [np.random.randint] para para criar um array de numeros de 1 a 10 com o tamanho do array de 100

O metodo np.bincount(array).argmax() foi utilizado com a ideia de verificar quantas vezes cada numero aparece dentro do array e apos isso verificar qual o numero que mais apareceu dentro do array

12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

In [99]:
import numpy as np

matriz = np.eye(4)
indices = np.arange(4)
matriz[indices, indices] = 7

print(matriz)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


Foi utilizado o método [np.eye] para criar uma matriz identidade de tamanho 4x4, preenchendo a diagonal principal com valores 1 e as demais posições com 0.

Foi utilizado o método [np.arange] para criar os índices de 0 a 3, que representam as posições da diagonal principal.

Foi utilizado o comando [matriz[indices, indices]] para acessar as posições da diagonal principal e substituí-las pelo valor 7.

13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.

In [100]:
import numpy as np

array = np.arange(2, 22, 2)

print("Array original: ")
print(array)

print("Soma cumulativa: ")
print(np.cumsum(array))

Array original: 
[ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: 
[  2   6  12  20  30  42  56  72  90 110]


Foi criado o array de numeros 2 a 22 pulando de 2 em 2 fazendo assim só ter numeros pares dentro do array

Para realizar a soma cumulativa foi utilizado o metodo np.cumsum dentro do proprio print com o array dentro do metodo

14. Calcule a diferença entre dois arrays de números aleatórios de mesmo
comprimento e encontre a média das diferenças.

In [101]:
import numpy as np

array1 = np.random.randint(1, 11, size=10)
array2 = np.random.randint(1, 11, size=10)

print("Array 1: ", array1)
print("Array 2: ", array2)

diferencaArray = array1 - array2

print("Diferença dos array's: ", diferencaArray)

print("Media da diferenca dos array's: ", np.mean(diferencaArray))

Array 1:  [ 1 10  2  7  3  1  8  3  5 10]
Array 2:  [9 7 7 6 3 5 7 5 1 7]
Diferença dos array's:  [-8  3 -5  1  0 -4  1 -2  4  3]
Media da diferenca dos array's:  -0.7


Foi utilizado o método [np.random.randint] para gerar dois arrays de números aleatórios de 1 a 10, ambos com tamanho de 10 componentes.

Foi utilizado o operador [-] para calcular a diferença entre os elementos correspondentes dos dois arrays.

Foi utilizado o método [np.mean] para calcular a média dos valores presentes no array de diferenças.

15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.


In [102]:
import numpy as np

array = np.random.randint(25, 76, size=20)

print("Array original: ", array)

array[array > 50] = 50

print("Array modificado: ", array)

Array original:  [52 31 57 53 37 45 55 28 38 34 44 67 65 37 62 39 29 54 66 43]
Array modificado:  [50 31 50 50 37 45 50 28 38 34 44 50 50 37 50 39 29 50 50 43]


Foi utilizado o método [np.random.randint] para gerar um array de números aleatórios de 25 a 75, com tamanho de 20 componentes.

Foi utilizado o comando [array > 50] para identificar os valores do array que são maiores que 50.

Foi utilizado o comando [array[array > 50] = 50] para substituir todos os valores maiores que 50 pelo valor 50.

16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.

In [103]:
import numpy as np

array = np.arange(12)
matriz3x4 = array.reshape(3,4)

print("Array original: ")
print(array)

print("Matriz 3x4: ")
print(matriz3x4)

Array original: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Matriz 3x4: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Foi utilizado o método [np.arange] para criar um array contendo os valores de 0 a 11, totalizando 12 elementos.

Foi utilizado o método [reshape] para reorganizar o array em uma matriz com 3 linhas e 4 colunas.

Foi utilizado o comando [print] para exibir o array original e a matriz 3x4 resultante.

17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz.

In [104]:
import numpy as np

matriz = np.random.randint(1, 11, size=(4,4))

posicao = np.arange(16).reshape((4,4))

resultado = matriz * posicao

print("Matriz original: ")
print(matriz)

print("Posicao: ")
print(posicao)

print("Resultado: ")
print(resultado)

Matriz original: 
[[ 1  5  2 10]
 [ 3  9  5 10]
 [ 7  8  2  4]
 [ 1  4  3  3]]
Posicao: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Resultado: 
[[ 0  5  4 30]
 [12 45 30 70]
 [56 72 20 44]
 [12 52 42 45]]


Foi utilizado o método [np.random.randint] para criar uma matriz 4x4 com números aleatórios de 1 a 10.

Foi utilizado o método [np.arange] para criar um array com os valores de 0 a 15 e o método [reshape] para organizá-lo em uma matriz 4x4.

Foi utilizado o operador [*] para multiplicar os elementos correspondentes da matriz original pelos elementos da matriz de posições.

Foi utilizado o comando [print] para exibir a matriz original, a matriz de posições e o resultado da multiplicação.

 18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 5 por 0.

In [105]:
import numpy as np

array = np.random.randint(1, 101, size=10)

print("Array original: ")
print(array)

array[array % 5 == 0] = 0

print("Array modificado: ")
print(array)

Array original: 
[65 47 68 98 32  4 79 73 38 29]
Array modificado: 
[ 0 47 68 98 32  4 79 73 38 29]


Foi utilizado o método [np.random.randint] para gerar um array de 10 números aleatórios entre 1 e 100.

Foi utilizado o operador [%] para verificar quais valores do array são divisíveis por 5, obtendo resto igual a 0.

Foi utilizado o comando [array[array % 5 == 0] = 0] para substituir por 0 todos os valores que são múltiplos de 5.


19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ângulo entre eles (produto escalar normalizado).

In [106]:
import numpy as np

array1 = np.random.randint(1,11, size=20)
array2 = np.random.randint(1,11, size=20)

produtoEscalar = np.dot(array1, array2)

normaArray1 = np.linalg.norm(array1)
normaArray2 = np.linalg.norm(array2)

angulo = np.arccos(produtoEscalar / (normaArray1 * normaArray2))

angulo = np.clip(angulo, -1.0, 1.0)

anguloRadianos = np.arccos(angulo)
anguloGraus = np.degrees(anguloRadianos)

print("Array 1: ", array1)
print("Array 2: ", array2)

print("Produto Escalar: ", produtoEscalar)

print("Angulo entre os arrays: ", anguloGraus)

Array 1:  [ 6  4  4 10  6  2  3  7  5  5  4  7  6  5  8 10 10  4  8  7]
Array 2:  [ 8  2  8  8 10  9  5  5  2  5  4  5  1  2  6  7  1  4  8  4]
Produto Escalar:  634
Angulo entre os arrays:  54.86466764595784


Foi utilizado o método [np.random.randint] para gerar dois arrays de 20 números aleatórios entre 1 e 10.

Foi utilizado o método [np.dot] para calcular o produto escalar entre os arrays.

Foi utilizado o método [np.linalg.norm] para calcular a norma dos arrays.

Foi utilizado o método [np.arccos] para calcular o ângulo entre os arrays.

Foi utilizado o método [np.degrees] para converter o ângulo de radianos para graus.

20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada linha.

In [107]:
import numpy as np

matriz = np.random.randint(1, 11, size=(4,4))

print("Matriz original: ")
print(matriz)

valorMinimo = np.min(matriz, axis=1)

print("Valor minimo de cada linha: ")
print(valorMinimo)

Matriz original: 
[[10  3  4  1]
 [ 9  5  9  8]
 [10 10  1  7]
 [10  8 10  1]]
Valor minimo de cada linha: 
[1 5 1 1]


Foi utilizado o método [np.random.randint] para criar uma matriz 4x4 com números aleatórios de 1 a 10.

Foi utilizado o método [np.min] para encontrar o menor valor de cada linha da matriz.

Foi utilizado o parâmetro [axis=1] no método [np.min] para indicar que o menor valor deve ser encontrado em cada linha da matriz.

## SciPy

1. Calcule a integral da função f(x) = x2 sin(x) no intervalo de 0 a π

In [108]:
import numpy as np
from scipy import integrate

def f(x):
  return x**2 * np.sin(x)

resultado, erroEstimado = integrate.quad(f, 0, np.pi)

print("Resultado da integral: ", resultado)
print("Erro estimado: ", erroEstimado)

Resultado da integral:  5.869604401089359
Erro estimado:  6.516569951530559e-14


Foi utilizada a biblioteca [scipy.integrate] para realizar o cálculo da integral definida.

Foi utilizada a função [integrate.quad] para calcular a integral de x² · sen(x) no intervalo de 0 a π.

Foi utilizado o valor [erroEstimado] para apresentar uma estimativa do erro do cálculo.

2. Resolva a equação diferencial dy/dx = x − y, com y(0) = 1, no intervalo de 0 a 10.

In [109]:
import numpy as np
from scipy import integrate

def f(x, y):
    return x - y

xSpan = (0, 10)
y0 = [1.0]

xEval = np.linspace(0, 10, 11)

solucao = integrate.solve_ivp(f, xSpan, y0, t_eval=xEval)

for xVal, yVal in zip(solucao.t, solucao.y[0]):
    print("x =", xVal, " | y(x) =", yVal)

x = 0.0  | y(x) = 1.0
x = 1.0  | y(x) = 0.7359216243371075
x = 2.0  | y(x) = 1.270615687212305
x = 3.0  | y(x) = 2.0994171070331364
x = 4.0  | y(x) = 3.036717242198936
x = 5.0  | y(x) = 4.013631188936788
x = 6.0  | y(x) = 5.004673943883074
x = 7.0  | y(x) = 6.002108361053508
x = 8.0  | y(x) = 7.000783713819767
x = 9.0  | y(x) = 8.000189802039149
x = 10.0  | y(x) = 9.000461488339488


Foi utilizada a função [integrate.solve_ivp] para resolver numericamente a equação diferencial dy/dx = x - y.

Foi definida a condição inicial [y0 = 1.0] e o intervalo de 0 a 10.

Foi utilizado o método [np.linspace] para criar 11 pontos entre 0 e 10.

Foi utilizado o comando [zip] para percorrer os valores de x e y e exibir os resultados da solução.


3. Encontre as raízes da função f(x) = xˆ4 − 3xˆ3 + 2 utilizando SciPy.

In [111]:
from scipy import optimize

def f(x):
  return x**4 - 3*x**3 + 2

raiz1 = optimize.fsolve(f, 1.0)[0]
raiz2 = optimize.fsolve(f, 3.0)[0]

print("Raiz 1: ", raiz1)
print("Raiz 2: ", raiz2)

Raiz 1:  1.0
Raiz 2:  2.919639565839426


Foi utilizada a função [optimize.fsolve] para encontrar numericamente as raízes da função x⁴ - 3x³ + 2.

Foi utilizado o valor [1.0] como aproximação inicial para encontrar a primeira raiz e [-1.0] para encontrar a segunda raiz.

Foi utilizado o comando [print] para exibir as raízes encontradas.

4. Use a função de otimização de SciPy para maximizar f(x) =−xˆ2+ 4x+ 1.

In [113]:
from scipy import optimize

def f(x):
  return -( -x[0]**2 + 4*x[0] + 1)

resultado = optimize.minimize(f, [0.0])
pontoMaximo = resultado.x[0]
valorMaximo = -resultado.fun

print("Ponto máximo (x): ", pontoMaximo)
print("Valor máximo: ", valorMaximo)

Ponto máximo (x):  2.000000026187685
Valor máximo:  4.999999999999999


Foi utilizada a função [optimize.minimize] para encontrar o ponto máximo da função [-x² + 4x + 1].

Foi utilizada a função negativa para transformar o problema de maximização em minimização.

Foi utilizado o comando [resultado.x] para obter o ponto máximo e [resultado.fun] para obter o valor máximo.

5. Calcule a transformada de Fourier de um sinal composto de sin(2πt) e
cos(4πt).

In [114]:
import numpy as np
from scipy import fft

t = np.linspace(0, 1, 500, endpoint=False)
sinal = np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)
transformadaSinal = fft.fft(sinal)

print("Primeiros 5 termos da transformada de Fourier: ", transformadaSinal[:5])

Primeiros 5 termos da transformada de Fourier:  [-8.32667268e-15-0.00000000e+00j -2.20934382e-14-2.50000000e+02j
  2.50000000e+02-3.41948692e-14j  1.56045512e-14-6.62279098e-15j
 -1.13100615e-14-3.29398128e-15j]


Foi utilizado o método [np.linspace] para criar 500 pontos no intervalo de 0 a 1.

Foi utilizada a função [np.sin] e [np.cos] para criar um sinal composto por duas ondas.

Foi utilizada a função [fft.fft] para calcular a transformada de Fourier do sinal.

Foi utilizado o comando [transformadaSinal[:5]] para exibir os 5 primeiros termos da transformada.

6. Encontre a matriz inversa de uma matriz 5x5 de números aleatórios.

In [115]:
import numpy as np
from scipy import linalg

np.random.seed(42)
matrizAleatoria = np.random.rand(5,5)
matrizInversa = linalg.inv(matrizAleatoria)

print("Matriz original: ")
print(matrizAleatoria)

print("Matriz inversa: ")
print(matrizInversa)

Matriz original: 
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]
Matriz inversa: 
[[  364.60350483   334.16789204   -91.41631021  -895.54602541
    -35.23406016]
 [ -351.86538626  -323.93604372    89.07808984   864.20754679
     35.93471989]
 [  584.80763977   538.00659297  -146.16417479 -1436.8998493
    -59.51982157]
 [ -234.80558669  -217.08098236    57.15090649   582.66687482
     22.50116178]
 [ -567.51216365  -519.48181002   143.11544206  1389.49392418
     58.52220068]]


Foi utilizado o método [np.random.rand] para criar uma matriz aleatória 5x5 com valores entre 0 e 1.

Foi utilizado o método [linalg.inv] para calcular a matriz inversa da matriz original.

Foi utilizado o comando [np.random.seed] para definir um valor fixo e gerar sempre a mesma matriz aleatória.
