<a href="https://colab.research.google.com/github/76Falcone/AulasInteligenciaArtificial/blob/main/Exerc%C3%ADciosBibliotecas_Python_Falcone_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios práticos em Python para explorar a aplicação de quatro bibliotecas diferentes.

## NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.


In [ ]:
import numpy as np

array = np.random.randint(10, 101, size=50)

print(array)

[45 35 87 11 20 70 30 11 79 62 33 66 40 28 34 74 46 10 62 97 25 21 44 36
 24 77 12 35 52 51 82 93 91 25 29 33 42 11 47 54 38 20 25 56 18 33 54 27
 90 14]


Foi utilizado o [.random] para randomizar os numeros e dentro dele o [.randint] para que fosse apenas numeros inteiros

Parametro de inicio 10 até o fim 100 com o tamanho de 50 numeros dentro do array



2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [ ]:
import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)

ultima_linha = matriz[-1]

print("Matriz completa:")
print(matriz)

print("\nÚltima linha:")
print(ultima_linha)

Matriz completa:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha:
[13 14 15 16]


Foi utilizado o [.arange] para gerar a sequência de números e junto a ele o [.reshape] para que fosse formatado em linhas e colunas.

Parâmetro de início 1 até o fim 17 (para incluir o 16) com o tamanho de 4x4 (4 linhas e 4 colunas) dentro da matriz.

E foi utilizado o índice [-1] na variável para extrair apenas a última linha da matriz.

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
`a 10ª posição por 1

In [ ]:
import numpy as np

array = np.zeros(15)

array[4:10] = 1

print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Foi utilizado o [.zeros] para criar um array apenas composto de 0(zeros) com a quantidade de 15

Foi utilizado o parametro [4:10] para colocar o valor 1 da posição 5 até a posição 10

4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

In [ ]:
import numpy as np

array = np.random.randint(1, 21, size=100)

mediana = np.median(array)
moda = np.bincount(array).argmax()

print("Array gerado:", array)
print("Mediana:", mediana)
print("Moda:", moda)


Array gerado: [ 6  6 17  8  4  8  6  2 14  3  9 17 17 10  6 12 16 19 14  1 12  2  1  3
 20 18 15 19 14 19  8  7 12 13  1  1 15 11 16  8  3 10  5 15  4  1 16  8
  7 10 16 15  8  1 15 15 19 19  4 14 10  5  1 17  3 14  2  1 17 13  9 15
 11  4 12  8  5  5 11 19 19 13  5 16 19 20  5 11  2 12 11  5  3  4 10 20
  3 19 11 11]
Mediana: 10.5
Moda: 19


Dentro da geração do array foi escolhido colocar o parametro de numeros de 1 a 20 para que existissem repetições

[np.median] foi utilizado para calcular a mediana do array

[np.bincount] foi utilizado para verificar quantas vezes cada numero apareceu dentro do array

[argmax()] foi utilizado na intenção de mostrar qual elemento apareceu mais vezes



5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por -3.

In [ ]:
import numpy as np

array = np.random.randint(1, 101, size=20)

print("Array original:")
print(array)

array[array % 3 == 0] = -3

print("Array modificado:")
print(array)

Array original:
[30 23 31 56 91 48 77  2 34 84 72 15 32 55 13 65 28 64 12 84]
Array modificado:
[-3 23 31 56 91 -3 77  2 34 -3 -3 -3 32 55 13 65 28 64 -3 -3]


Foi criado um array aonde gera 20 numeros inteiros de 1 a 100

Utilizando o calculo [array % 3 == 0] vai calcular o modulo do de cada numero do array, caso o valor seja 0 no final o numero sera alterado para [-3]

6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna.

In [ ]:
import numpy as np

matriz = np.random.rand(5, 5)

print("Matriz completa:")
print(matriz)

soma_colunas = np.sum(matriz, axis=0)
print("Soma de cada coluna:", soma_colunas)


Matriz completa:
[[0.43145058 0.99831261 0.22207    0.77796099 0.22302143]
 [0.11380368 0.70563451 0.27129552 0.22130883 0.06704798]
 [0.12863495 0.5543265  0.35707538 0.43493585 0.15262331]
 [0.20049903 0.23444488 0.49452375 0.87523977 0.54863231]
 [0.12864356 0.88512515 0.92465686 0.87361091 0.31306845]]
Soma de cada coluna: [1.00303181 3.37784363 2.26962151 3.18305635 1.30439348]


A função np.random.rand(5, 5) faz uma matriz de 5 po 5 com apenas numeros de 0 a 1

A função axis=0 ela trabalha no eixo vertical, somando com a função np.sum realiza a soma de cada coluna da matriz de forma separada

7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [ ]:
import numpy as np

array1 = np.random.randint(1,15, size=10)
array2 = np.random.randint(1,15, size=10)

print("Array 1: ", array1)
print("Array 2: ", array2)

print("Correlação: ", np.corrcoef(array1, array2))

Array 1:  [ 5  7 12 10  8  2  2 14  7 10]
Array 2:  [11  5 13  1  7  5 10  1  8 10]
Correlação:  [[ 1.         -0.23696697]
 [-0.23696697  1.        ]]


Para a criação dos array`s foi utilizado o comando [np.random.randint] para que fosse gerado numeros inteiros aleatorios

Para a correlação foi utilizada a função np.corrcoef() com as 2 array`s criadas dentro da função


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.


In [ ]:
import numpy as np

matriz = np.random.randint(1, 11, size=(3,3))

print("Matriz original:")
print(matriz)

print("Matriz ao quadrado:")
print(matriz**2)

Matriz original:
[[10  6  9]
 [ 1  4  7]
 [ 9  3  3]]
Matriz ao quadrado:
[[100  36  81]
 [  1  16  49]
 [ 81   9   9]]


Foi criado a matriz com numeros aleatorios e inteiros de 1 a 10 com a matriz de por 3

Para elevar a matriz ao quadrado não foi criado uma variavel nova para isso, e sim utilizando apenas uma formula matematica para elevar apenas no print

9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.


In [ ]:
import numpy as np

array = np.random.randint(1, 11, size=10)

print("Array original:")
print(array)

valorMin = np.min(array)
valorMax = np.max(array)

arrayNormalizado = (array - valorMin) / (valorMax - valorMin)

arrayNormalizado = np.round(arrayNormalizado, 2)

print("Array normalizado:")
print(arrayNormalizado)


Array original:
[5 2 2 6 4 9 3 5 1 5]
Array normalizado:
[0.5  0.12 0.12 0.62 0.38 1.   0.25 0.5  0.   0.5 ]


Foi utilizado o metodo [np.random.randint] para gerar um array de numeros de 1 a 10 com o tamanho do array de 10 componentes

Foi utilizado os metodos [np.min] e [np.max] para acessar o menor e o maior numero do array

Foi utilizada a fórmula de normalização (x - mínimo) / (máximo - mínimo) para calcular o valor normalizado de cada número do array, transformando os valores para uma escala entre 0 e 1.


10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

In [ ]:
import numpy as np

matriz = np.eye(6)

indices = np.arange(6)
matriz[indices, indices] = np.arange(1, 7)

print(matriz)



[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


Foi utilizado o método [np.eye] para criar uma matriz identidade de tamanho 6x6, preenchendo a diagonal principal com valores 1 e as demais posições com 0.

Foi utilizado o método [np.arange] para criar os índices de 0 a 5, que representam as posições da diagonal principal da matriz.

Foi utilizado o comando [matriz[indices, indices]] para acessar as posições da diagonal principal e substituí-las pelos valores de 1 a 6.

Foi utilizado o método [np.arange(1, 7)] para gerar os valores crescentes de 1 a 6, que foram colocados na diagonal principal da matriz.


11. Gere um array de 100 números inteiros e encontre o valor que mais se
repete no array.

In [ ]:
import numpy as np

array = np.random.randint(1, 11, size=100)

print("Array gerado: ")
print(array)

moda = np.bincount(array).argmax()

print("\nValor que mais se repete: ", moda)

Array gerado: 
[ 4  1  8  4  4  4  4 10  9  3  4  4 10  7 10  4  4  1  8  9  1  9  4  1
  9  6  3  7 10 10  6  1  7  2  2  1  9  9  7  3  2  9  8  7 10  7  7  3
  2  2  4  3  9  1  6  5 10  9  2  9  8  9  7  3  7 10  3  3  8  9  1  1
 10  7 10  7 10  3  4  5  5  8  4  2  5 10  7  1  2  8  9  8  1  2  8  9
  2  5  8  6]

Valor que mais se repete:  9


Foi utilizado o metodo [np.random.randint] para para criar um array de numeros de 1 a 10 com o tamanho do array de 100

O metodo np.bincount(array).argmax() foi utilizado com a ideia de verificar quantas vezes cada numero aparece dentro do array e apos isso verificar qual o numero que mais apareceu dentro do array

12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

In [ ]:
import numpy as np

matriz = np.eye(4)
indices = np.arange(4)
matriz[indices, indices] = 7

print(matriz)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


Foi utilizado o método [np.eye] para criar uma matriz identidade de tamanho 4x4, preenchendo a diagonal principal com valores 1 e as demais posições com 0.

Foi utilizado o método [np.arange] para criar os índices de 0 a 3, que representam as posições da diagonal principal.

Foi utilizado o comando [matriz[indices, indices]] para acessar as posições da diagonal principal e substituí-las pelo valor 7.

13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.

In [ ]:
import numpy as np

array = np.arange(2, 22, 2)

print("Array original: ")
print(array)

print("Soma cumulativa: ")
print(np.cumsum(array))

Array original: 
[ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: 
[  2   6  12  20  30  42  56  72  90 110]


Foi criado o array de numeros 2 a 22 pulando de 2 em 2 fazendo assim só ter numeros pares dentro do array

Para realizar a soma cumulativa foi utilizado o metodo np.cumsum dentro do proprio print com o array dentro do metodo

14. Calcule a diferença entre dois arrays de números aleatórios de mesmo
comprimento e encontre a média das diferenças.

In [ ]:
import numpy as np

array1 = np.random.randint(1, 11, size=10)
array2 = np.random.randint(1, 11, size=10)

print("Array 1: ", array1)
print("Array 2: ", array2)

diferencaArray = array1 - array2

print("Diferença dos array's: ", diferencaArray)

print("Media da diferenca dos array's: ", np.mean(diferencaArray))

Array 1:  [6 1 6 9 8 1 1 1 3 2]
Array 2:  [7 3 9 3 7 8 3 9 4 2]
Diferença dos array's:  [-1 -2 -3  6  1 -7 -2 -8 -1  0]
Media da diferenca dos array's:  -1.7


Foi utilizado o método [np.random.randint] para gerar dois arrays de números aleatórios de 1 a 10, ambos com tamanho de 10 componentes.

Foi utilizado o operador [-] para calcular a diferença entre os elementos correspondentes dos dois arrays.

Foi utilizado o método [np.mean] para calcular a média dos valores presentes no array de diferenças.

15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.


In [ ]:
import numpy as np

array = np.random.randint(25, 76, size=20)

print("Array original: ", array)

array[array > 50] = 50

print("Array modificado: ", array)

Array original:  [58 34 74 44 57 48 71 57 31 37 73 34 25 67 69 32 54 27 52 60]
Array modificado:  [50 34 50 44 50 48 50 50 31 37 50 34 25 50 50 32 50 27 50 50]


Foi utilizado o método [np.random.randint] para gerar um array de números aleatórios de 25 a 75, com tamanho de 20 componentes.

Foi utilizado o comando [array > 50] para identificar os valores do array que são maiores que 50.

Foi utilizado o comando [array[array > 50] = 50] para substituir todos os valores maiores que 50 pelo valor 50.

16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.

In [ ]:
import numpy as np

array = np.arange(12)
matriz3x4 = array.reshape(3,4)

print("Array original: ")
print(array)

print("Matriz 3x4: ")
print(matriz3x4)

Array original: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Matriz 3x4: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Foi utilizado o método [np.arange] para criar um array contendo os valores de 0 a 11, totalizando 12 elementos.

Foi utilizado o método [reshape] para reorganizar o array em uma matriz com 3 linhas e 4 colunas.

Foi utilizado o comando [print] para exibir o array original e a matriz 3x4 resultante.

17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz.

In [ ]:
import numpy as np

matriz = np.random.randint(1, 11, size=(4,4))

posicao = np.arange(16).reshape((4,4))

resultado = matriz * posicao

print("Matriz original: ")
print(matriz)

print("Posicao: ")
print(posicao)

print("Resultado: ")
print(resultado)

Matriz original: 
[[ 9  9  3  2]
 [ 4  1  7  7]
 [ 8  2  3  2]
 [ 2  8  9 10]]
Posicao: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Resultado: 
[[  0   9   6   6]
 [ 16   5  42  49]
 [ 64  18  30  22]
 [ 24 104 126 150]]


Foi utilizado o método [np.random.randint] para criar uma matriz 4x4 com números aleatórios de 1 a 10.

Foi utilizado o método [np.arange] para criar um array com os valores de 0 a 15 e o método [reshape] para organizá-lo em uma matriz 4x4.

Foi utilizado o operador [*] para multiplicar os elementos correspondentes da matriz original pelos elementos da matriz de posições.

Foi utilizado o comando [print] para exibir a matriz original, a matriz de posições e o resultado da multiplicação.

 18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 5 por 0.

In [33]:
import numpy as np

array = np.random.randint(1, 101, size=10)

print("Array original: ")
print(array)

array[array % 5 == 0] = 0

print("Array modificado: ")
print(array)

Array original: 
[56 35 97 87 27 57 63 94 36 40]
Array modificado: 
[56  0 97 87 27 57 63 94 36  0]


Foi utilizado o método [np.random.randint] para gerar um array de 10 números aleatórios entre 1 e 100.

Foi utilizado o operador [%] para verificar quais valores do array são divisíveis por 5, obtendo resto igual a 0.

Foi utilizado o comando [array[array % 5 == 0] = 0] para substituir por 0 todos os valores que são múltiplos de 5.


19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ângulo entre eles (produto escalar normalizado).

In [34]:
import numpy as np

array1 = np.random.randint(1,11, size=20)
array2 = np.random.randint(1,11, size=20)

produtoEscalar = np.dot(array1, array2)

normaArray1 = np.linalg.norm(array1)
normaArray2 = np.linalg.norm(array2)

angulo = np.arccos(produtoEscalar / (normaArray1 * normaArray2))

angulo = np.clip(angulo, -1.0, 1.0)

anguloRadianos = np.arccos(angulo)
anguloGraus = np.degrees(anguloRadianos)

print("Array 1: ", array1)
print("Array 2: ", array2)

print("Produto Escalar: ", produtoEscalar)

print("Angulo entre os arrays: ", anguloGraus)

Array 1:  [ 5 10  9  6  4  8  1 10  9 10  5 10  9  2  6  9  4  4  7  8]
Array 2:  [9 7 4 2 4 8 9 7 7 9 4 8 4 6 8 7 3 6 4 9]
Produto Escalar:  870
Angulo entre os arrays:  62.54694076859198


Foi utilizado o método [np.random.randint] para gerar dois arrays de 20 números aleatórios entre 1 e 10.

Foi utilizado o método [np.dot] para calcular o produto escalar entre os arrays.

Foi utilizado o método [np.linalg.norm] para calcular a norma dos arrays.

Foi utilizado o método [np.arccos] para calcular o ângulo entre os arrays.

Foi utilizado o método [np.degrees] para converter o ângulo de radianos para graus.