<a href="https://colab.research.google.com/github/76Falcone/AulasInteligenciaArtificial/blob/main/Exerc%C3%ADciosBibliotecas_Python_Falcone_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios práticos em Python para explorar a aplicação de quatro bibliotecas diferentes.

## NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.


In [ ]:
import numpy as np

array = np.random.randint(10, 101, size=50)

print(array)

[27 25 82 32 20 30 45 39 38 81 23 78 83 62 57 38 12 50 27 76 13 25 37 70
 23 19 36 34 12 67 26 89 30 50 84 41 78 43 20 32 62 22 41 32 87 18 82 47
 55 54]


Foi utilizado o [.random] para randomizar os numeros e dentro dele o [.randint] para que fosse apenas numeros inteiros

Parametro de inicio 10 até o fim 100 com o tamanho de 50 numeros dentro do array



2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [ ]:
import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)

ultima_linha = matriz[-1]

print("Matriz completa:")
print(matriz)

print("\nÚltima linha:")
print(ultima_linha)

Matriz completa:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha:
[13 14 15 16]


Foi utilizado o [.arange] para gerar a sequência de números e junto a ele o [.reshape] para que fosse formatado em linhas e colunas.

Parâmetro de início 1 até o fim 17 (para incluir o 16) com o tamanho de 4x4 (4 linhas e 4 colunas) dentro da matriz.

E foi utilizado o índice [-1] na variável para extrair apenas a última linha da matriz.

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
`a 10ª posição por 1

In [ ]:
import numpy as np

array = np.zeros(15)

array[4:10] = 1

print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Foi utilizado o [.zeros] para criar um array apenas composto de 0(zeros) com a quantidade de 15

Foi utilizado o parametro [4:10] para colocar o valor 1 da posição 5 até a posição 10

4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

In [ ]:
import numpy as np

array = np.random.randint(1, 21, size=100)

mediana = np.median(array)
moda = np.bincount(array).argmax()

print("Array gerado:", array)
print("Mediana:", mediana)
print("Moda:", moda)


Array gerado: [13  6 20  7 12 13 13  2 16  4  3 15 14 12  1 16 13 10  5  4 15 17  8 15
  3  1 19 11 15 20  3 19 12  8 12  6  7 12  2  9  6 15 12  3 13  5 15 20
  9 19 20  2  7  8 12  6 15 14  6 12  5 19  7 12 13 11  3 20 20 12 16 12
  6 20  7 14 14 16 15 10  8 15 17 12  1 16  3  1  4 11  8  3 17  8 13 18
  6 20  1 11]
Mediana: 12.0
Moda: 12


Dentro da geração do array foi escolhido colocar o parametro de numeros de 1 a 20 para que existissem repetições

[np.median] foi utilizado para calcular a mediana do array

[np.bincount] foi utilizado para verificar quantas vezes cada numero apareceu dentro do array

[argmax()] foi utilizado na intenção de mostrar qual elemento apareceu mais vezes



5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por -3.

In [ ]:
import numpy as np

array = np.random.randint(1, 101, size=20)

print("Array original:")
print(array)

array[array % 3 == 0] = -3

print("Array modificado:")
print(array)

Array original:
[16 83 85 31 77 11 86  8 21  6 19 61 33 64 31 62 83 56 94 33]
Array modificado:
[16 83 85 31 77 11 86  8 -3 -3 19 61 -3 64 31 62 83 56 94 -3]


Foi criado um array aonde gera 20 numeros inteiros de 1 a 100

Utilizando o calculo [array % 3 == 0] vai calcular o modulo do de cada numero do array, caso o valor seja 0 no final o numero sera alterado para [-3]