<a href="https://colab.research.google.com/github/76Falcone/AulasInteligenciaArtificial/blob/main/Exerc%C3%ADciosBibliotecas_Python_Falcone_6B_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios práticos em Python para explorar a aplicação de quatro bibliotecas diferentes.

## NumPy

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.


In [37]:
import numpy as np

array = np.random.randint(10, 101, size=50)

print(array)

[ 56  38  13  24  36  12  28  26  22  65  58  20  73  66  32  19  55  59
  47  36  68  11  24  73  99  69 100  79  56  68  10  16  50  17  35  38
  79  65  31  51  13  13  26  52  21  69  24  61  67  23]


Foi utilizado o [.random] para randomizar os numeros e dentro dele o [.randint] para que fosse apenas numeros inteiros

Parametro de inicio 10 até o fim 100 com o tamanho de 50 numeros dentro do array



2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [38]:
import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)

ultima_linha = matriz[-1]

print("Matriz completa:")
print(matriz)

print("\nÚltima linha:")
print(ultima_linha)

Matriz completa:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha:
[13 14 15 16]


Foi utilizado o [.arange] para gerar a sequência de números e junto a ele o [.reshape] para que fosse formatado em linhas e colunas.

Parâmetro de início 1 até o fim 17 (para incluir o 16) com o tamanho de 4x4 (4 linhas e 4 colunas) dentro da matriz.

E foi utilizado o índice [-1] na variável para extrair apenas a última linha da matriz.

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
`a 10ª posição por 1

In [39]:
import numpy as np

array = np.zeros(15)

array[4:10] = 1

print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Foi utilizado o [.zeros] para criar um array apenas composto de 0(zeros) com a quantidade de 15

Foi utilizado o parametro [4:10] para colocar o valor 1 da posição 5 até a posição 10

4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

In [40]:
import numpy as np

array = np.random.randint(1, 21, size=100)

mediana = np.median(array)
moda = np.bincount(array).argmax()

print("Array gerado:", array)
print("Mediana:", mediana)
print("Moda:", moda)


Array gerado: [14 18 19  6 10 17 19  9 14 15  6  4 12 11  6  5 17 16  9 17 15  3  7  3
 20  4  4 12 16 18 19 14 12 11  4  7  5  2  5  6  7 14  2 11 13  1  4  6
  8 16 13  5  6 17 18 19  7 20 19  5 11  9 20  9  8 11  2 14 13  5 18 10
  3 14 12  5 17  2  1 14  6  6 15  4  3  4 10  3  1 13 14  7 13  6 18 13
 20  3 17  8]
Mediana: 10.0
Moda: 6


Dentro da geração do array foi escolhido colocar o parametro de numeros de 1 a 20 para que existissem repetições

[np.median] foi utilizado para calcular a mediana do array

[np.bincount] foi utilizado para verificar quantas vezes cada numero apareceu dentro do array

[argmax()] foi utilizado na intenção de mostrar qual elemento apareceu mais vezes



5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por -3.

In [41]:
import numpy as np

array = np.random.randint(1, 101, size=20)

print("Array original:")
print(array)

array[array % 3 == 0] = -3

print("Array modificado:")
print(array)

Array original:
[30 77 83 55 83 32 88 22 94 60 99 51 94 64 80 90 14 61 13 72]
Array modificado:
[-3 77 83 55 83 32 88 22 94 -3 -3 -3 94 64 80 -3 14 61 13 -3]


Foi criado um array aonde gera 20 numeros inteiros de 1 a 100

Utilizando o calculo [array % 3 == 0] vai calcular o modulo do de cada numero do array, caso o valor seja 0 no final o numero sera alterado para [-3]

6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna.

In [42]:
import numpy as np

matriz = np.random.rand(5, 5)

print("Matriz completa:")
print(matriz)

soma_colunas = np.sum(matriz, axis=0)
print("Soma de cada coluna:", soma_colunas)


Matriz completa:
[[0.9131767  0.27630192 0.87760261 0.51267314 0.14374536]
 [0.39866503 0.53346301 0.70286382 0.52126339 0.43862428]
 [0.39098186 0.6862064  0.63217451 0.89228726 0.77480177]
 [0.06882623 0.24186279 0.14262832 0.44803192 0.23811476]
 [0.95934595 0.766827   0.31889503 0.9232104  0.86995887]]
Soma de cada coluna: [2.73099578 2.50466113 2.6741643  3.29746611 2.46524503]


A função np.random.rand(5, 5) faz uma matriz de 5 po 5 com apenas numeros de 0 a 1

A função axis=0 ela trabalha no eixo vertical, somando com a função np.sum realiza a soma de cada coluna da matriz de forma separada

7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [43]:
import numpy as np

array1 = np.random.randint(1,15, size=10)
array2 = np.random.randint(1,15, size=10)

print("Array 1: ", array1)
print("Array 2: ", array2)

print("Correlação: ", np.corrcoef(array1, array2))

Array 1:  [ 3  8 10  7  2  8  3 14 12  3]
Array 2:  [13 14 11  5 10 11  9  1 13  5]
Correlação:  [[ 1.         -0.17523014]
 [-0.17523014  1.        ]]


Para a criação dos array`s foi utilizado o comando [np.random.randint] para que fosse gerado numeros inteiros aleatorios

Para a correlação foi utilizada a função np.corrcoef() com as 2 array`s criadas dentro da função


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.


In [44]:
import numpy as np

matriz = np.random.randint(1, 11, size=(3,3))

print("Matriz original:")
print(matriz)

print("Matriz ao quadrado:")
print(matriz**2)

Matriz original:
[[5 8 6]
 [4 1 3]
 [6 6 3]]
Matriz ao quadrado:
[[25 64 36]
 [16  1  9]
 [36 36  9]]


Foi criado a matriz com numeros aleatorios e inteiros de 1 a 10 com a matriz de por 3

Para elevar a matriz ao quadrado não foi criado uma variavel nova para isso, e sim utilizando apenas uma formula matematica para elevar apenas no print

9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.


In [45]:
import numpy as np

array = np.random.randint(1, 11, size=10)

print("Array original:")
print(array)

valorMin = np.min(array)
valorMax = np.max(array)

arrayNormalizado = (array - valorMin) / (valorMax - valorMin)

arrayNormalizado = np.round(arrayNormalizado, 2)

print("Array normalizado:")
print(arrayNormalizado)


Array original:
[ 6 10 10 10  3  5  4  4  7  6]
Array normalizado:
[0.43 1.   1.   1.   0.   0.29 0.14 0.14 0.57 0.43]


Foi utilizado o metodo [np.random.randint] para gerar um array de numeros de 1 a 10 com o tamanho do array de 10 componentes

Foi utilizado os metodos [np.min] e [np.max] para acessar o menor e o maior numero do array

Foi utilizada a fórmula de normalização (x - mínimo) / (máximo - mínimo) para calcular o valor normalizado de cada número do array, transformando os valores para uma escala entre 0 e 1.


10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

In [46]:
import numpy as np

matriz = np.eye(6)

indices = np.arange(6)
matriz[indices, indices] = np.arange(1, 7)

print(matriz)



[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


Foi utilizado o método [np.eye] para criar uma matriz identidade de tamanho 6x6, preenchendo a diagonal principal com valores 1 e as demais posições com 0.

Foi utilizado o método [np.arange] para criar os índices de 0 a 5, que representam as posições da diagonal principal da matriz.

Foi utilizado o comando [matriz[indices, indices]] para acessar as posições da diagonal principal e substituí-las pelos valores de 1 a 6.

Foi utilizado o método [np.arange(1, 7)] para gerar os valores crescentes de 1 a 6, que foram colocados na diagonal principal da matriz.


11. Gere um array de 100 números inteiros e encontre o valor que mais se
repete no array.

In [47]:
import numpy as np

array = np.random.randint(1, 11, size=100)

print("Array gerado: ")
print(array)

moda = np.bincount(array).argmax()

print("\nValor que mais se repete: ", moda)

Array gerado: 
[ 9  8  8  5  4  4  5 10  3  2  5  5  8  4 10  9  9  4  1  9  2  4  5  7
  7  3  1  7  8  2 10  9  3  7  7  1  3  9  2  3  7  4  5  2  4  7  6  9
  2  6  1  3  1  4  4  8  1  8  7  4 10  7  3  5  4  4  3  3  1  5  1  2
  1  7  2  2  1 10  9  6  4  4  6  8  9  5  2  5  4  8  8  6  6  3 10 10
 10  8  6  1]

Valor que mais se repete:  4


Foi utilizado o metodo [np.random.randint] para para criar um array de numeros de 1 a 10 com o tamanho do array de 100

O metodo np.bincount(array).argmax() foi utilizado com a ideia de verificar quantas vezes cada numero aparece dentro do array e apos isso verificar qual o numero que mais apareceu dentro do array

12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

In [48]:
import numpy as np

matriz = np.eye(4)
indices = np.arange(4)
matriz[indices, indices] = 7

print(matriz)

[[7. 0. 0. 0.]
 [0. 7. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


Foi utilizado o método [np.eye] para criar uma matriz identidade de tamanho 4x4, preenchendo a diagonal principal com valores 1 e as demais posições com 0.

Foi utilizado o método [np.arange] para criar os índices de 0 a 3, que representam as posições da diagonal principal.

Foi utilizado o comando [matriz[indices, indices]] para acessar as posições da diagonal principal e substituí-las pelo valor 7.

13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.

In [49]:
import numpy as np

array = np.arange(2, 22, 2)

print("Array original: ")
print(array)

print("Soma cumulativa: ")
print(np.cumsum(array))

Array original: 
[ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: 
[  2   6  12  20  30  42  56  72  90 110]


Foi criado o array de numeros 2 a 22 pulando de 2 em 2 fazendo assim só ter numeros pares dentro do array

Para realizar a soma cumulativa foi utilizado o metodo np.cumsum dentro do proprio print com o array dentro do metodo

14. Calcule a diferença entre dois arrays de números aleatórios de mesmo
comprimento e encontre a média das diferenças.

In [50]:
import numpy as np

array1 = np.random.randint(1, 11, size=10)
array2 = np.random.randint(1, 11, size=10)

print("Array 1: ", array1)
print("Array 2: ", array2)

diferencaArray = array1 - array2

print("Diferença dos array's: ", diferencaArray)

print("Media da diferenca dos array's: ", np.mean(diferencaArray))

Array 1:  [2 6 5 9 7 9 1 3 9 1]
Array 2:  [ 7  8  2  1  7 10  3  7  5  4]
Diferença dos array's:  [-5 -2  3  8  0 -1 -2 -4  4 -3]
Media da diferenca dos array's:  -0.2


Foi utilizado o método [np.random.randint] para gerar dois arrays de números aleatórios de 1 a 10, ambos com tamanho de 10 componentes.

Foi utilizado o operador [-] para calcular a diferença entre os elementos correspondentes dos dois arrays.

Foi utilizado o método [np.mean] para calcular a média dos valores presentes no array de diferenças.

15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.


In [51]:
import numpy as np

array = np.random.randint(25, 76, size=20)

print("Array original: ", array)

array[array > 50] = 50

print("Array modificado: ", array)

Array original:  [33 39 47 58 32 49 56 69 37 58 53 65 53 49 72 36 59 75 28 69]
Array modificado:  [33 39 47 50 32 49 50 50 37 50 50 50 50 49 50 36 50 50 28 50]


Foi utilizado o método [np.random.randint] para gerar um array de números aleatórios de 25 a 75, com tamanho de 20 componentes.

Foi utilizado o comando [array > 50] para identificar os valores do array que são maiores que 50.

Foi utilizado o comando [array[array > 50] = 50] para substituir todos os valores maiores que 50 pelo valor 50.

16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.

In [52]:
import numpy as np

array = np.arange(12)
matriz3x4 = array.reshape(3,4)

print("Array original: ")
print(array)

print("Matriz 3x4: ")
print(matriz3x4)

Array original: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Matriz 3x4: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Foi utilizado o método [np.arange] para criar um array contendo os valores de 0 a 11, totalizando 12 elementos.

Foi utilizado o método [reshape] para reorganizar o array em uma matriz com 3 linhas e 4 colunas.

Foi utilizado o comando [print] para exibir o array original e a matriz 3x4 resultante.

17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz.

In [53]:
import numpy as np

matriz = np.random.randint(1, 11, size=(4,4))

posicao = np.arange(16).reshape((4,4))

resultado = matriz * posicao

print("Matriz original: ")
print(matriz)

print("Posicao: ")
print(posicao)

print("Resultado: ")
print(resultado)

Matriz original: 
[[ 5  7  8  9]
 [ 3  4  4  7]
 [ 5  1 10  2]
 [10  4  3  6]]
Posicao: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Resultado: 
[[  0   7  16  27]
 [ 12  20  24  49]
 [ 40   9 100  22]
 [120  52  42  90]]


Foi utilizado o método [np.random.randint] para criar uma matriz 4x4 com números aleatórios de 1 a 10.

Foi utilizado o método [np.arange] para criar um array com os valores de 0 a 15 e o método [reshape] para organizá-lo em uma matriz 4x4.

Foi utilizado o operador [*] para multiplicar os elementos correspondentes da matriz original pelos elementos da matriz de posições.

Foi utilizado o comando [print] para exibir a matriz original, a matriz de posições e o resultado da multiplicação.

 18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 5 por 0.

In [54]:
import numpy as np

array = np.random.randint(1, 101, size=10)

print("Array original: ")
print(array)

array[array % 5 == 0] = 0

print("Array modificado: ")
print(array)

Array original: 
[49 67 76 11 58 40 71 44 82  7]
Array modificado: 
[49 67 76 11 58  0 71 44 82  7]


Foi utilizado o método [np.random.randint] para gerar um array de 10 números aleatórios entre 1 e 100.

Foi utilizado o operador [%] para verificar quais valores do array são divisíveis por 5, obtendo resto igual a 0.

Foi utilizado o comando [array[array % 5 == 0] = 0] para substituir por 0 todos os valores que são múltiplos de 5.


19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ângulo entre eles (produto escalar normalizado).

In [55]:
import numpy as np

array1 = np.random.randint(1,11, size=20)
array2 = np.random.randint(1,11, size=20)

produtoEscalar = np.dot(array1, array2)

normaArray1 = np.linalg.norm(array1)
normaArray2 = np.linalg.norm(array2)

angulo = np.arccos(produtoEscalar / (normaArray1 * normaArray2))

angulo = np.clip(angulo, -1.0, 1.0)

anguloRadianos = np.arccos(angulo)
anguloGraus = np.degrees(anguloRadianos)

print("Array 1: ", array1)
print("Array 2: ", array2)

print("Produto Escalar: ", produtoEscalar)

print("Angulo entre os arrays: ", anguloGraus)

Array 1:  [5 1 7 3 2 4 5 1 2 4 9 9 6 7 7 8 5 9 9 3]
Array 2:  [10  2  2  3  2  4  2  8 10  7 10  2  3  3  1  8  5  3  4  1]
Produto Escalar:  470
Angulo entre os arrays:  40.81244875965773


Foi utilizado o método [np.random.randint] para gerar dois arrays de 20 números aleatórios entre 1 e 10.

Foi utilizado o método [np.dot] para calcular o produto escalar entre os arrays.

Foi utilizado o método [np.linalg.norm] para calcular a norma dos arrays.

Foi utilizado o método [np.arccos] para calcular o ângulo entre os arrays.

Foi utilizado o método [np.degrees] para converter o ângulo de radianos para graus.

20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada linha.

In [56]:
import numpy as np

matriz = np.random.randint(1, 11, size=(4,4))

print("Matriz original: ")
print(matriz)

valorMinimo = np.min(matriz, axis=1)

print("Valor minimo de cada linha: ")
print(valorMinimo)

Matriz original: 
[[ 8  2 10  8]
 [ 7  3  9  1]
 [ 7  4  4  3]
 [ 8 10  9  4]]
Valor minimo de cada linha: 
[2 1 3 4]


Foi utilizado o método [np.random.randint] para criar uma matriz 4x4 com números aleatórios de 1 a 10.

Foi utilizado o método [np.min] para encontrar o menor valor de cada linha da matriz.

Foi utilizado o parâmetro [axis=1] no método [np.min] para indicar que o menor valor deve ser encontrado em cada linha da matriz.